# seed: 0
collection: null
experiment:
  log_dir: '../logs'
  data_dir: '../data'
dataset: 'cifar10-valid'
search_space:
  fast_mode: True
numerics:
  method: 'bayesian_quadrature'
  initialisation:
    num_samples: 50
  evaluation_budget: 50
  surrogate:
    warping: null
  acquisition:
    strategy: 'top-valid'
    num_initial: 1024
    mutate_size: 128
  kernel_integration:
    num_samples: 2048
    batch_size: null
  sum_space: 'logit'
  nas_options:
    seed: 777
    train_epochs: 200
    swag: False
  test_batch_size: 10000
debug_options:
  smoke_test: False
  test_set: 'grid'
