# seed: 489238141
collection: null
# load_collection: 'collection_cifar10_bq-us_09151213'
load_collection: 'collection_cifar10_bq-ei_10031432'
experiment:
  log_dir: '../logs'
  data_dir: '../data'
dataset: 'cifar10-valid'
search_space:
  fast_mode: True
numerics:
  method: 'neural_ensemble_search_regularised_evolution'
  evaluation_budget: 150
  # load_design_set: 3403
  population_size: 50
  num_parent_candidates: 10
  ensemble_size: 3
  sum_space: 'probability'
  nas_options:
    seed: 777
    train_epochs: 200
    batch_size: 10000
  test_batch_size: 10000
debug_options:
  smoke_test: False