# seed: 0
collection: null
experiment:
  log_dir: '../logs'
  data_dir: '../data'
  smoke_test: False
dataset: 'cifar10-valid'
search_space:
  fast_mode: True
numerics:
  method: 'bayesian_quadrature'
  initialisation:
    num_samples: 10
  evaluation_budget: 150
  surrogate:
    warping: 'linearised-sqrt'
  acquisition:
    strategy: 'uncertainty_sampling'
    num_initial: 1024
  kernel_integration:
    num_samples: 2048
    batch_size: null
  sum_space: 'probability'
  nas_options:
    seed: 777
    train_epochs: 200
  test_batch_size: 10000
